### ISSUE TITLE
bug do None e estética

### ISSUE THREAD

**Issue by LeudoNeto** [Franky03/UnderTraps#1]
- [x] Aparece none no cabeçalho da lista de dados, por causa da função hea conter "print(line())" ao invés de só "line()" que já era responsável por printar linhas.
- [x] Estética: espaço no final das string de input, pra resposta do usuário não ficar colada ao texto da pergunta.

**Comment by Franky03** [comment]
@LeudoNeto os erros já foram atualizados na branch [level_two](https://github.com/Franky03/UnderTraps/tree/level_two), obrigado pelo aviso!!
